apiVersion: v1
kind: Template
labels:
  app: pgexporter
  template: pgexporter-buildconfig
metadata:
  annotations:
    description: Postgres Exporter - BuildConfig
      see https://github.com/Worteks/docker-pgexporter
    iconClass: icon-openshift
    openshift.io/display-name: Postgres Exporter
    tags: database,mongodb
  name: pgexporter-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Postgres Exporter images
    labels:
      name: pgexporter-${FRONTNAME}-${POSTGRES_EXPORTER_REPOSITORY_REF}
    name: pgexporter-${FRONTNAME}-${POSTGRES_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${POSTGRES_EXPORTER_REPOSITORY_URL}
        ref: "${POSTGRES_EXPORTER_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: pgexporter-${FRONTNAME}:${POSTGRES_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: POSTGRES_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: POSTGRES_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your Postgres exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-pgexporter.git
