apiVersion: v1
kind: Template
labels:
  app: pgexporter
  template: pgexporter-imagestream
metadata:
  annotations:
    description: Postgres Exporter - ImageStream
      see https://github.com/Worteks/docker-pgexporter
    iconClass: icon-openshift
    openshift.io/display-name: Postgres Exporter
    tags: database,postgres
  name: pgexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Postgres Exporter image
    name: pgexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
