apiVersion: v1
kind: Template
labels:
  app: pgexporter
  template: pgexporter-secret
metadata:
  annotations:
    description: Postgres Exporter - Secret
      see https://github.com/Worteks/docker-pgexporter
    iconClass: icon-openshift
    openshift.io/display-name: Postgres Exporter
    tags: database,postgres
  name: pgexporter-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-admin_password: "{.data['database-admin-password']}"
      template.openshift.io/expose-database_name: "{.data['database-name']}"
      template.openshift.io/expose-password: "{.data['database-password']}"
      template.openshift.io/expose-username: "{.data['database-user']}"
    name: postgres-${FRONTNAME}
  stringData:
    database-admin-password: ${POSTGRES_ADMIN_PASSWORD}
    database-name: ${POSTGRES_DATABASE}
    database-password: ${POSTGRES_PASSWORD}
    database-user: ${POSTGRES_USER}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: POSTGRES_ADMIN_PASSWORD
  description: Password for the database admin user.
  displayName: Postgres Admin Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
- name: POSTGRES_DATABASE
  description: Name of the Postgres database accessed.
  displayName: Postgres Database Name
  required: true
  value: sampledb
- name: POSTGRES_PASSWORD
  description: Password for the Postgres connection user.
  displayName: Postgres Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true
- name: POSTGRES_USER
  description: Username for Postgres user that will be used for accessing the database.
  displayName: Postgres Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  required: true
